[project]
authors = ["1Meracle1 <bahorin.ivan@gmail.com>"]
channels = ["https://conda.modular.com/max", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "mojo_xcb_win_manager"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
